# Generated by Django 4.2.13 on 2024-06-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
